rastgelesago = ['https://i.pinimg.com/736x/ed/d5/03/edd5032117dac523c4275e0c997d8545.jpg',
				'https://i.pinimg.com/736x/b0/4a/a1/b04aa18b0575a07278c40da695b4f149.jpg',
				'https://pbs.twimg.com/media/EQ10gKBWkAA1gj4.jpg',
				'https://pbs.twimg.com/media/DbuX98yWkAEceyM.jpg',
				'https://i.milliyet.com.tr/MolatikGaleri/2019/06/10/fft373_mf32867512.Jpeg',
				'https://canerkorkmazli.com.tr/wp-content/uploads/sagopa-kajmer-bursa-konseri-1.jpg',
				'https://www.konya.bel.tr/bldfoto/11/klt/sagopa_6.jpg',
				'https://maksatbilgi.com/wp-content/uploads/2019/04/Sagopa-Kajmer-2019-Foto-Galeri-17.jpg',
				'https://c.tenor.com/dGzeJ6myqs4AAAAC/snake-dance.gif',
				'https://s8.gifyu.com/images/ezgif-2-6bfceba1921.gif',
				'https://j.gifs.com/vVMVzq.gif',
				'https://j.gifs.com/KeJaV8.gif',
				'https://pbs.twimg.com/media/D0FsBpZXgAAlNkc.jpg',
				'https://c.tenor.com/Bei7bqjm-qwAAAAd/sagopa-sagopa-dans.gif']

sesa = ['Kötürüm oldu ince ruhlar ordusu.',
        'Son arzusunda anlaşıldı ölümün korkusu, tuhaf kokusu.',
        'Sükut lütfu dileyen ellerim telaşla açılıverdi göklere.',
        'Panik içinde koşar adımla kaçışıyordu tüm dualarım derinlere.',
        'Bense dipte boğuluyordum, tek savaşıyordum en derinde.',
        'Kimler önüne geçebilir zamanın akışının, cümlelerimin noktalarına kaç zamanda ulaşırım.',
        'Yaşarım, iskeletler diyarında bir et parçasıyım. Sisteminde virüsü saklar her beyin.',
        'Benim nefesimdenmişçesine yalanın. Yok yerin.',
        'Aklım kendine mezar kazabileceğin kadar derin.',
        'Terkedilmiş evler kadar yalnız, mevsimsizim. Çalınmayı bekleyen kapı ziliyim, ben isimsizim.',
        'İster istemez her şeyim sende rehin.',
        'Ne yanlış bir karar masası, sen ne kötü bir hakimsin.',
        'Bu ne zor bi dosya, sen ne kolay bir kararsın, senden görünmüyor önüm, meğer ne kolaymış fikri ölüm.',
        'Ben bir aç, sense tok misal, sen olmadan ne işe yarar en güzel kumsal, ne olur gitme kal.',
        'Ya biriktirdiğim onca yarınlık, ben yarımken yarınla bu gün arasında nedir farklılık?',
        'Ben nakit bir sevgiyim, karşılıksız hediyeyim, susuz bir bedeviyim.',
        'En zor anda bir devadır hoş sesin, kendinle utanmadan konuş!',
        'Düşman kelimesinin anlamını arkadaş sıfatını taşıyanlardan öğrendim.',
        'Karıştı yarınım bitti dün, tedirgin bugün.',
        'Öylesine kibirli ki biber yakmadan bırakmaz rahat.',
        'Aşım soğudu yine iştahsızlık elinde oyuncak etti açlığımı.',
        'Ruhum işgalden kurtulmaz vatan.',
        'Dudaklarımda bal yok, oysa tek dilekti mutluluk.',
        'Öldürmek için beni benden silahımı bekleme.. Cümleni bitir artık tekleme!',
        'Sen şahane bir uçurtmasın, ben de senin ipinim unutmayasın! Bensiz söyle ne işe yararsın?',
        'Bugün eğer yapmazsam olurum yarın pişman, dediklerini yaptığı için olabilir insan yarın pişman.',
        'Anlamaktı zor olan, ki kolaya kaçmak alınmaktı her şeye.',
        'Sensiz geçen her gün için kapıma çelenk gönder.',
        'Kahır bu adamı yere devirdi, kulaklarım sağır. Hoş sesinle bana bağır, hafiflesin yüküm ağır.',
        'Benim gerçekliğimin ölümsüzlüğü yaşatmakta hüznümü. Kendimi kendime hediye ederek kutladım son doğum günümü.',
        'Zaman soframdaki en lezzetli mühim yemek.',
        'Trilyon da olsan harcanacaksın.',
        'Pişmanlık asla kaçamayacağın bir canavar, elleri bazen öldürür, bazen sertçe yakalar.',
        'Yanan ışıklarımı kaplayacak kadar karanlığım var.',
        'İçimde şefini kaybeden bir orkestranın hüznü var, dışımda Charlie Chaplin gülüşü.',
        'Karanlık olman aydınlık değersiz bir pırlanta.',
        'Hayrından umutsuzum getirme bari şerrini.',
        'Tek yabancı bendim evde ve bir yalancı mumdu doğan güneş.',
        'Bir vesikalık gülen çocuktum, yüzüme bakarak ağladım, yüzleşirken kendimle, hıçkırıklarımla savaşır oldum.',
        'Gideni yolcu etti gözlerim ve gelene merhaba dedi bu kimsesiz dilim. Ortalarda gezinen oldu dilenci ellerim.',
        'Yokluğun bir ölüme benzetildiği şiir tadında varlığın bir saçmalıkmış.',
        'Sadakatin güvenimin sonu mudur, sen kaderdin.',
        'Yaşanmışlık kolumda büyüyen bebeğin ergenlik hali.',
        'Sonsuzluğun beni tanımadı, yalnızlığım fırtınalı. Kuklalar sepette, çek al egolarını.',
        'Dünya gezengenler arasında tek bitchtir.',
        'Kafadar olmak dostluğun yalan adı.',
        'Kuvvete dayanamayan adalet aciz, adalete dayanamayan kuvvet zalimdir.',
        'Tasanın etrafında gezgin olmuş insanlar, kısacık molalarda tanıdılar mutluluk denen kelimeyi.',
        'Geçici bir dövmesin. Şeklini çizdi tanrı topraklara; vakti gelince kazma kürekle silineceksin.',
        'Nefsinin dişleri kalmamış seni dişlemekten, yazık.',
        'Ben baktıkça ağaçlara, kalbimin kuşları konmak ister dallara.',
        'Rüzgar şiddeti bilmez duvarın ardına saklananlar.',
        'Sadece bana bak bana yalan söyleyeceksen önce gözlerimle anlaş.',
        'Hiçbir tehdit tenime rüzgar kadar zarar veremedi.',
        'Motiflerini işledim, yürek adınla eş değer ki; bildiğim tek şiirsin, anlamın derin, aklımda kal.',
        'Komada ezgiler, ve intiharda tüm kadercil yazgılar.',
        'Sudan sebeple kavga çıkaran insanoğlu, yordu aklı kötüye, iyiyi yetime terk ettik.',
        'Sevaplarım günahlarımla sevişir halde.',
        'Varlık ruhu terk eder; gözüm gözünden ayrılınca, bendeki aşk altın misali ağırlığınca.',
        'Sensiz benlik yokluk demek, kalbim sana emekçi.',
        'Saniyeler dakikalarla yapar alışverişi. Saatler seni alır benden korkarım olamaz gelişi.',
        'Odamın hayaletisin sessizliğine aşığım.',
        'Kursağımda düğümlenir laflar sana içimi açmak istedikçe. Sen ne kadar anlarsın ben anlatmak istesem de?',
        'Sensin benim en zor savaşlarımda çelik yelek.',
        'Bana dokunma! Yanımı senle doldurma! İsteksizce bir teklikle kalmalıyım yalnızca.',
        'Hazan umursamadı yaprakları katletti alayını. Çöpçü oldu rüzgarım esti geçti göremedin.',
        'Dil ateştir biraz suyla söndürülmesi mümkündür, tırnaklarını aşındıran çözemediğin bu kör düğümdür.',
        'Sabır tüm sıkıntıların anahtarıdır, doğrudur. Düş kırıklıklarım sonucu ruhum yorgundur.',
        'Sen gözümde dikensin bana hoş bir gül gerek.',
        'Çevre sakinim çok aksileşmiş, içlerinde 5 kuruşluk hırslarıyla kavrulur durumda, kaç liraydı onurunuz?',
        'Kaç dünya güzeli öldü boşa giden orgazmlarda?',
        'Tek kurşun bitirebilse gari bu hayatı, bari bin kurşun atın da gönlüm doysun ahali.',
        "Aldım yaşamı yanıma kutu kolacasına, üç dikişte dibe vurdum, depozitosunu Tanrım'a ödüyorum.",
        'Özür bir borç gibiydi en zor ödenen hali. Kalbi hacize verdim oysa borçlu sendin.',
        'Onuru zedeler alaya vurulan her doğru.',
        'Rüşvetiydi kaderin ilk görüşte aşk!',
        'Kavalyem olsa öpebilir miyim ölümü?',
        'Hayat çoklu yaşanır, ruhlarsa teklidir.',
        'Çıldırdığını düşünürler, o büyük düşünürler.',
        '"Keşke konuşmasaydım" dersin. Meğer buymuş ilk dersin. Zor iş, kolay gelsin.',
        'Elin boşta kalır, tutmadıklarında. Gözün yaşta kalır, anlamadıklarında. Sesin titrer konuşmaya çabaladığında ardarda.',
        'Kaybetmedim hiçbir zaman dürüstlüğümü, ama dürüstlükten çok kaybettim.',
        'Vazgeçtim inan, kendimden çoktan, ama senden olmuyor kendimi koparamıyorum bir an.',
        'Sanırım tüm suç bende, seçtiğim seçeneklerde.',
        'Dünya gemisinde söyle kim korsan?',
        '"Merhaba"yla başlamıştı, son sözüydü "Hoşça kal".',
        "İsterdim ben de düşünmemek ama düşürüyo' düşünce ana bazen. Sen bakma, ben 'Unuttum' derim ama, her şey aklımda hâlen..",
        "Bu hayat bize bir gün bakar elbet. Bir üşütür bir yakar elbet. Ruhumuz darmadağın, paramparça.. Düştüğü yerden bir gün kalkar elbet.",
        "Eğer ki gönlün benimle olursa Yemen'de bile olsan yanımdasın. Eğer ki gönlün benimle değilse yanımda bile olsan uzaktasın.",
        'Ben ne savaşlar verdim kendime bir rabbim şahit, sor ne zaman vurdun kendini en son. Katilim oldum her gece nedense.',
        'Duvarlar üzerime geldikçe kendime 10 parmaklı bir surat yaptım...',
        'Misaldi bence cennet ve cehennem masaldı, okunan tüm hikayeler hayaldi.']

slol = ['https://youtu.be/ORJUUA97Zc4',
	  'https://youtu.be/ORJUUA97Zc4',
      'https://youtu.be/ORJUUA97Zc4',
      'https://youtu.be/ORJUUA97Zc4',
      'https://youtu.be/ORJUUA97Zc4',
      'https://youtu.be/uJInYI-aolQ',
      'https://youtu.be/uJInYI-aolQ',
      'https://youtu.be/7H1H94Q2ehU',
      'https://youtu.be/7H1H94Q2ehU',
      'https://youtu.be/7H1H94Q2ehU',
      'https://youtu.be/PV6bEuytTvs',
      'https://youtu.be/PV6bEuytTvs',
      'https://youtu.be/PV6bEuytTvs',
      'https://youtu.be/PV6bEuytTvs',
      'https://youtu.be/PV6bEuytTvs',
      'https://youtu.be/_yt6y-2CpcE',
      'https://youtu.be/_yt6y-2CpcE',
      'https://youtu.be/X6B46ln_ZAM',
      'https://youtu.be/E7nnRGo8xRE',
      'https://youtu.be/E7nnRGo8xRE',
      'https://youtu.be/E7nnRGo8xRE',
      'https://youtu.be/E7nnRGo8xRE',
      'https://youtu.be/no3NwKB33Dw',
      'https://youtu.be/xAw8P4___gs?t=2197',
      'https://youtu.be/xAw8P4___gs?t=2197',
      'https://youtu.be/bA5kG5NFph0',
      'https://youtu.be/BwvgQAyV5Fk',
      'https://youtu.be/3qoTbxD7b3o',
      'https://youtu.be/3qoTbxD7b3o',
      'https://youtu.be/3qoTbxD7b3o',
      'https://youtu.be/WHPt5ZYxPcI',
      'https://youtu.be/WHPt5ZYxPcI',
      'https://youtu.be/WHPt5ZYxPcI',
      'https://youtu.be/WHPt5ZYxPcI',
      'https://youtu.be/jnt1_otPus4',
      'https://youtu.be/jnt1_otPus4',
      'https://youtu.be/9COiHbjguxM',
      'https://youtu.be/up269McwqDM',
      'https://youtu.be/up269McwqDM',
      'https://youtu.be/up269McwqDM',
      'https://youtu.be/Z-Zw2QlSCA0',
      'https://youtu.be/Z-Zw2QlSCA0',
      'https://youtu.be/QKGuLoax2RY',
      'https://youtu.be/QKGuLoax2RY',
      'https://youtu.be/_2UPd9Pkp-0',
      'https://youtu.be/_2UPd9Pkp-0',
      'https://youtu.be/9NL_b9e4UFE',
      'https://youtu.be/9NL_b9e4UFE',
      'https://youtu.be/9NL_b9e4UFE',
      'https://youtu.be/SRe-Yz5CVPE',
      'https://youtu.be/SRe-Yz5CVPE',
      'https://youtu.be/MaHrmtOjKbM',
      'https://youtu.be/MaHrmtOjKbM',
      'https://youtu.be/MaHrmtOjKbM',
      'https://youtu.be/xPwGbgBoJEk',
      'https://youtu.be/QOTQZbjjd5c',
      'https://youtu.be/QOTQZbjjd5c',
      'https://youtu.be/GKChoCsY9SQ',
      'https://youtu.be/8v0DXX9RXbM',
      'https://youtu.be/8v0DXX9RXbM',
      'https://youtu.be/8v0DXX9RXbM',
      'https://youtu.be/8v0DXX9RXbM',
      'https://youtu.be/xAw8P4___gs?t=847',
      'https://youtu.be/xAw8P4___gs?t=847',
      'https://youtu.be/xAw8P4___gs?t=847',
      'https://youtu.be/shmugrVVJAg',
      'https://youtu.be/SNFf4997odg',
      'https://youtu.be/SNFf4997odg',
      'https://youtu.be/SNFf4997odg',
      'https://youtu.be/q9TKJxNgBlk',
      'https://youtu.be/q9TKJxNgBlk',
      'https://youtu.be/xG2CGy3Dy60',
      'https://youtu.be/xG2CGy3Dy60',
      'https://youtu.be/OpW-WWwcsjY',
      'https://youtu.be/OpW-WWwcsjY',
      'https://youtu.be/J3o8UnKu3_o',
      'https://youtu.be/J3o8UnKu3_o',
      'https://youtu.be/PDaoKtAQKgA',
      'https://youtu.be/J6l9cbiqCNI',
      'https://youtu.be/J6l9cbiqCNI',
      'https://youtu.be/J6l9cbiqCNI',
      'https://youtu.be/xwOto0m-sXg',
      'https://youtu.be/4IcvHlK0SZA',
      'https://youtu.be/Y-8e0M1WR_c',
      'https://youtu.be/E5yJ1LEsg48',
      'https://youtu.be/AMw787ISSmg',
      'https://youtu.be/nKzZd37QzrA',
      'https://youtu.be/j82SmDAvhag',
      'https://youtu.be/oC9ASVOvIwo',
      'https://youtu.be/UJrpxClziJw',
      'https://youtu.be/UJrpxClziJw',
      'https://youtu.be/WYb4xPOAV3U?t=766']

kapak = ['https://upload.wikimedia.org/wikipedia/tr/e/e4/Bir_Pesimistin_G%C3%B6zya%C5%9Flar%C4%B1.jpg',
		 'https://upload.wikimedia.org/wikipedia/tr/e/e4/Bir_Pesimistin_G%C3%B6zya%C5%9Flar%C4%B1.jpg',
		 'https://upload.wikimedia.org/wikipedia/tr/e/e4/Bir_Pesimistin_G%C3%B6zya%C5%9Flar%C4%B1.jpg',
		 'https://upload.wikimedia.org/wikipedia/tr/e/e4/Bir_Pesimistin_G%C3%B6zya%C5%9Flar%C4%B1.jpg',
		 'https://upload.wikimedia.org/wikipedia/tr/e/e4/Bir_Pesimistin_G%C3%B6zya%C5%9Flar%C4%B1.jpg',
		 'https://upload.wikimedia.org/wikipedia/tr/e/e4/Bir_Pesimistin_G%C3%B6zya%C5%9Flar%C4%B1.jpg',
		 'https://upload.wikimedia.org/wikipedia/tr/e/e4/Bir_Pesimistin_G%C3%B6zya%C5%9Flar%C4%B1.jpg',
		 'https://upload.wikimedia.org/wikipedia/tr/0/00/Ikimizi-anlatan-bir%C5%9Fey.jpg',
		 'https://upload.wikimedia.org/wikipedia/tr/0/00/Ikimizi-anlatan-bir%C5%9Fey.jpg',
		 'https://upload.wikimedia.org/wikipedia/tr/0/00/Ikimizi-anlatan-bir%C5%9Fey.jpg',
		 'https://upload.wikimedia.org/wikipedia/tr/thumb/4/4d/Saydam-odalar-2012.jpg/250px-Saydam-odalar-2012.jpg',
		 'https://upload.wikimedia.org/wikipedia/tr/thumb/4/4d/Saydam-odalar-2012.jpg/250px-Saydam-odalar-2012.jpg',
		 'https://upload.wikimedia.org/wikipedia/tr/thumb/4/4d/Saydam-odalar-2012.jpg/250px-Saydam-odalar-2012.jpg',
		 'https://upload.wikimedia.org/wikipedia/tr/thumb/4/4d/Saydam-odalar-2012.jpg/250px-Saydam-odalar-2012.jpg',
		 'https://upload.wikimedia.org/wikipedia/tr/thumb/4/4d/Saydam-odalar-2012.jpg/250px-Saydam-odalar-2012.jpg',
		 'https://upload.wikimedia.org/wikipedia/tr/9/99/Romantizma.jpg',
		 'https://upload.wikimedia.org/wikipedia/tr/9/99/Romantizma.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/e/e4/Bir_Pesimistin_G%C3%B6zya%C5%9Flar%C4%B1.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/thumb/8/83/%C5%9Eark%C4%B1-koleksiyoncusu.jpg/800px-%C5%9Eark%C4%B1-koleksiyoncusu.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/thumb/8/83/%C5%9Eark%C4%B1-koleksiyoncusu.jpg/800px-%C5%9Eark%C4%B1-koleksiyoncusu.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/thumb/8/83/%C5%9Eark%C4%B1-koleksiyoncusu.jpg/800px-%C5%9Eark%C4%B1-koleksiyoncusu.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/thumb/8/83/%C5%9Eark%C4%B1-koleksiyoncusu.jpg/800px-%C5%9Eark%C4%B1-koleksiyoncusu.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/e/e4/Bir_Pesimistin_G%C3%B6zya%C5%9Flar%C4%B1.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/1/1a/Sagopa-kajmer-kolera-bendeki-sen.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/1/1a/Sagopa-kajmer-kolera-bendeki-sen.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/d/da/Sagopa-Kajmer-Kalp-Hastasi.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/e/e4/Bir_Pesimistin_G%C3%B6zya%C5%9Flar%C4%B1.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/7/76/K%C3%B6t%C3%BC_insanlar%C4%B1_tan%C4%B1ma_senesi.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/7/76/K%C3%B6t%C3%BC_insanlar%C4%B1_tan%C4%B1ma_senesi.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/7/76/K%C3%B6t%C3%BC_insanlar%C4%B1_tan%C4%B1ma_senesi.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/7/76/K%C3%B6t%C3%BC_insanlar%C4%B1_tan%C4%B1ma_senesi.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/7/76/K%C3%B6t%C3%BC_insanlar%C4%B1_tan%C4%B1ma_senesi.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/7/76/K%C3%B6t%C3%BC_insanlar%C4%B1_tan%C4%B1ma_senesi.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/7/76/K%C3%B6t%C3%BC_insanlar%C4%B1_tan%C4%B1ma_senesi.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/thumb/8/83/%C5%9Eark%C4%B1-koleksiyoncusu.jpg/800px-%C5%9Eark%C4%B1-koleksiyoncusu.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/thumb/8/83/%C5%9Eark%C4%B1-koleksiyoncusu.jpg/800px-%C5%9Eark%C4%B1-koleksiyoncusu.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/7/76/K%C3%B6t%C3%BC_insanlar%C4%B1_tan%C4%B1ma_senesi.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/e/e4/Bir_Pesimistin_G%C3%B6zya%C5%9Flar%C4%B1.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/e/e4/Bir_Pesimistin_G%C3%B6zya%C5%9Flar%C4%B1.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/e/e4/Bir_Pesimistin_G%C3%B6zya%C5%9Flar%C4%B1.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/9/99/Romantizma.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/9/99/Romantizma.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/9/99/Romantizma.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/9/99/Romantizma.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/9/99/Romantizma.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/9/99/Romantizma.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/e/e4/Bir_Pesimistin_G%C3%B6zya%C5%9Flar%C4%B1.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/e/e4/Bir_Pesimistin_G%C3%B6zya%C5%9Flar%C4%B1.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/e/e4/Bir_Pesimistin_G%C3%B6zya%C5%9Flar%C4%B1.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/7/76/K%C3%B6t%C3%BC_insanlar%C4%B1_tan%C4%B1ma_senesi.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/7/76/K%C3%B6t%C3%BC_insanlar%C4%B1_tan%C4%B1ma_senesi.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/7/76/K%C3%B6t%C3%BC_insanlar%C4%B1_tan%C4%B1ma_senesi.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/7/76/K%C3%B6t%C3%BC_insanlar%C4%B1_tan%C4%B1ma_senesi.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/7/76/K%C3%B6t%C3%BC_insanlar%C4%B1_tan%C4%B1ma_senesi.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/9/99/Romantizma.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/e/e4/Bir_Pesimistin_G%C3%B6zya%C5%9Flar%C4%B1.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/e/e4/Bir_Pesimistin_G%C3%B6zya%C5%9Flar%C4%B1.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/9/99/Romantizma.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/6/6d/Kafile.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/6/6d/Kafile.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/6/6d/Kafile.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/6/6d/Kafile.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/1/1a/Sagopa-kajmer-kolera-bendeki-sen.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/1/1a/Sagopa-kajmer-kolera-bendeki-sen.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/1/1a/Sagopa-kajmer-kolera-bendeki-sen.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/e/e4/Bir_Pesimistin_G%C3%B6zya%C5%9Flar%C4%B1.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/7/76/K%C3%B6t%C3%BC_insanlar%C4%B1_tan%C4%B1ma_senesi.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/7/76/K%C3%B6t%C3%BC_insanlar%C4%B1_tan%C4%B1ma_senesi.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/7/76/K%C3%B6t%C3%BC_insanlar%C4%B1_tan%C4%B1ma_senesi.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/e/e4/Bir_Pesimistin_G%C3%B6zya%C5%9Flar%C4%B1.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/e/e4/Bir_Pesimistin_G%C3%B6zya%C5%9Flar%C4%B1.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/e/e4/Bir_Pesimistin_G%C3%B6zya%C5%9Flar%C4%B1.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/e/e4/Bir_Pesimistin_G%C3%B6zya%C5%9Flar%C4%B1.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/9/99/Romantizma.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/9/99/Romantizma.jpg',
		 'https://upload.wikimedia.org/wikipedia/tr/e/e4/Bir_Pesimistin_G%C3%B6zya%C5%9Flar%C4%B1.jpg',
		 'https://upload.wikimedia.org/wikipedia/tr/e/e4/Bir_Pesimistin_G%C3%B6zya%C5%9Flar%C4%B1.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/d/da/Sagopa-Kajmer-Kalp-Hastasi.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/5/52/Sagopa-kajmer-pesimist-ep-6-ahmak-islatan.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/5/52/Sagopa-kajmer-pesimist-ep-6-ahmak-islatan.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/5/52/Sagopa-kajmer-pesimist-ep-6-ahmak-islatan.jpg',
         'https://images.genius.com/a3982ada022e29ee6a173a31b688e325.800x800x1.png',
         'https://upload.wikimedia.org/wikipedia/tr/6/6f/Sagopa_Kajmer_-_Sarkastik.jpg',
         'https://t2.genius.com/unsafe/288x288/https%3A%2F%2Fimages.genius.com%2F0b540e95ab860035890ac352c4527de5.1000x1000x1.jpg',
         'https://upload.wikimedia.org/wikipedia/tr/e/e7/Sagopa_Kajmer_%26_Go-Khan_-_Yunus_EP.jpg',
         'https://t2.genius.com/unsafe/251x251/https%3A%2F%2Fimages.genius.com%2Fda37512d44001d4bdb2a0ca95617db96.640x640x1.jpg',
         'https://images.genius.com/7d43d09f7cbf781f8f2cf3718d6fba9f.1000x1000x1.jpg',
         'https://images.genius.com/7d43d09f7cbf781f8f2cf3718d6fba9f.1000x1000x1.jpg',
         'https://s2.dmcdn.net/v/17Nth1Vj_lwJKAOjm/x1080',
         'https://scontent.fist13-1.fna.fbcdn.net/v/t1.6435-9/175337608_4202789106452205_2313742554995777322_n.jpg?_nc_cat=104&ccb=1-7&_nc_sid=8bfeb9&_nc_ohc=Nq58r8p3li0AX-FEnR9&_nc_ht=scontent.fist13-1.fna&oh=00_AT8Z8iRDwgsdhb2VJwsjFTU3DMZLtKUcLa86W1qv6G00_w&oe=62D03EDB',
         'https://scontent.fist13-1.fna.fbcdn.net/v/t1.6435-9/175337608_4202789106452205_2313742554995777322_n.jpg?_nc_cat=104&ccb=1-7&_nc_sid=8bfeb9&_nc_ohc=Nq58r8p3li0AX-FEnR9&_nc_ht=scontent.fist13-1.fna&oh=00_AT8Z8iRDwgsdhb2VJwsjFTU3DMZLtKUcLa86W1qv6G00_w&oe=62D03EDB',
         'https://upload.wikimedia.org/wikipedia/tr/e/e4/Bir_Pesimistin_G%C3%B6zya%C5%9Flar%C4%B1.jpg']
         
alb = ['Gerilim 99',
       'Yeraltı Operasyonu',
       'Toplama Kampı',
       'Pesimist EP',
       'Pesimist EP 2',
       'Pesimist EP 3',
       'Pesimist EP 4',
       'Pesimist EP 5',
       '10 Kurşun',
       'Sözlerim Silahım',
       'One Second',
       'Sagopa Kajmer',
       'İhtiyar Heyeti',
       'BPG',
       'Disstortion EP',
       'Romantizma',
       'Kafile',
       'İkimizi Anlatan Bir Şey',
       'KİTS',
       'Saykodelik EP',
       'Şarkı Koleksiyoncusu',
       'Bendeki Sen',
       'Saydam Odalar',
       'Kalp Hastası',
       'Ahmak Islatan (Pesimist EP 6)',
       'Sarkastik EP',
       'Yunus EP',
       'Tek',
       'Kağıt Kesikleri']
       
albfoto = ['https://images.genius.com/69027150be0b559555af714f512b1c0a.450x450x1.png',
           'https://upload.wikimedia.org/wikipedia/tr/e/e6/Yeraltioperasyonu.jpg',
           '',
           'https://upload.wikimedia.org/wikipedia/tr/f/fd/Sagopa_Kajmer_Pesimist_EP_1_alb%C3%BCm_kapa%C4%9F%C4%B1.jpg',
           'https://upload.wikimedia.org/wikipedia/tr/4/49/Sagopa_Kajmer_Pesimist_EP_2_alb%C3%BCm_kapa%C4%9F%C4%B1.png',
           'https://upload.wikimedia.org/wikipedia/tr/4/48/Pesimist-ep-3.png',
           'https://upload.wikimedia.org/wikipedia/tr/1/1f/Pesimist-ep-4.jpg',
           'https://upload.wikimedia.org/wikipedia/tr/6/6c/Pesimistep5.jpg',
           'https://images.genius.com/60cb04036cd11f4c0d0602eb94dca861.600x600x1.jpg',
           'https://upload.wikimedia.org/wikipedia/tr/thumb/3/3d/Sagopa_sozlerimsilahim.jpg/250px-Sagopa_sozlerimsilahim.jpg',
           '',
           'https://upload.wikimedia.org/wikipedia/tr/9/9c/Sagopakajmeralb%C3%BCm%C3%BC.jpg',
           'https://upload.wikimedia.org/wikipedia/tr/thumb/f/fd/%C4%B0htiyar_Heyeti.jpg/250px-%C4%B0htiyar_Heyeti.jpg',
           'https://upload.wikimedia.org/wikipedia/tr/e/e4/Bir_Pesimistin_G%C3%B6zya%C5%9Flar%C4%B1.jpg',
           'https://upload.wikimedia.org/wikipedia/tr/thumb/a/ae/Disstortion-ep.jpg/250px-Disstortion-ep.jpg',
           'https://upload.wikimedia.org/wikipedia/tr/9/99/Romantizma.jpg',
           'https://upload.wikimedia.org/wikipedia/tr/6/6d/Kafile.jpg',
           'https://upload.wikimedia.org/wikipedia/tr/0/00/Ikimizi-anlatan-bir%C5%9Fey.jpg',
           'https://upload.wikimedia.org/wikipedia/tr/7/76/K%C3%B6t%C3%BC_insanlar%C4%B1_tan%C4%B1ma_senesi.jpg',
           'https://upload.wikimedia.org/wikipedia/tr/thumb/d/d4/Saykodelik-ep.jpg/800px-Saykodelik-ep.jpg',
           'https://upload.wikimedia.org/wikipedia/tr/thumb/8/83/%C5%9Eark%C4%B1-koleksiyoncusu.jpg/800px-%C5%9Eark%C4%B1-koleksiyoncusu.jpg',
           'https://upload.wikimedia.org/wikipedia/tr/1/1a/Sagopa-kajmer-kolera-bendeki-sen.jpg',
           'https://upload.wikimedia.org/wikipedia/tr/thumb/4/4d/Saydam-odalar-2012.jpg/250px-Saydam-odalar-2012.jpg',
           'https://upload.wikimedia.org/wikipedia/tr/d/da/Sagopa-Kajmer-Kalp-Hastasi.jpg',
           'https://upload.wikimedia.org/wikipedia/tr/5/52/Sagopa-kajmer-pesimist-ep-6-ahmak-islatan.jpg',
           'https://upload.wikimedia.org/wikipedia/tr/6/6f/Sagopa_Kajmer_-_Sarkastik.jpg',
           'https://upload.wikimedia.org/wikipedia/tr/e/e7/Sagopa_Kajmer_%26_Go-Khan_-_Yunus_EP.jpg',
           'https://upload.wikimedia.org/wikipedia/tr/e/ed/Sagopa_Kajmer_Tek.jpeg',
           'https://images.genius.com/7d43d09f7cbf781f8f2cf3718d6fba9f.1000x1000x1.jpg']
           